" some reasonable defaults, like syntax highlighting
source /usr/share/vim/vim??/defaults.vim 

" enable plugins
execute pathogen#infect()

" enable powerline if we have support
if has("python3")
    let g:powerline_pycmd="python3"
    set laststatus=2
    set rtp+=~/.local/lib/python3/site-packages/powerline/bindings/vim

    python3 from powerline.vim import setup as powerline_setup
    python3 powerline_setup()
    python3 del powerline_setup
endif

" some settings
set hlsearch
set tabstop=4
set shiftwidth=4
set expandtab
set foldmethod=syntax
set mouse=a

" default unfolded
au BufWinEnter * normal zR
" set nofoldenable

" enable ycm
" ycm causes soooo many problems, let's just not
" let g:ycm_server_python_interpreter = '/usr/bin/python2'
" let g:ycm_global_ycm_extra_conf = '/usr/share/vim/vimfiles/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
" let g:ycm_autoclose_preview_window_after_completion = 1
" let g:ycm_confirm_extra_conf = 1
" let g:ycm_extra_conf_globlist = ['~/Arduino/bare_arduino/*']
" " let g:ycm_goto_buffer_command = 'split-or-existing-window'
" " let g:ycm_goto_buffer_command = 'split'

let g:AutoPairs = {'(':')', '[':']', '{':'}'}

" helpful keybindings
nnoremap <silent> <C-l> :noh<CR>
"noremap gy <C-w>s:YcmCompleter GoTo<CR>

" not so helpful keybindings
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
