" some reasonable defaults, like syntax highlighting
source /usr/share/vim/vim8?/defaults.vim 

execute pathogen#infect()

" enable powerline
let g:powerline_pycmd="python3"
set laststatus=2
set rtp+=~/.local/lib/python3.6/site-packages/powerline/bindings/vim

python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup

" some settings
set hlsearch
set tabstop=4
set shiftwidth=4
set expandtab
set foldmethod=syntax

" default unfolded
au BufWinEnter * normal zR
" set nofoldenable

" enable ycm
let g:ycm_server_python_interpreter = '/usr/bin/python2'
let g:ycm_global_ycm_extra_conf = '/usr/share/vim/vimfiles/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
let g:ycm_autoclose_preview_window_after_completion = 1

let g:AutoPairs = {'(':')', '[':']', '{':'}'}

" helpful keybindings
nnoremap <silent> <C-l> :noh<CR>

" not so helpful keybindings
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
